ONE-DIMENSIONAL ARRAY

In [46]:
import numpy as np 

# Creates a one dimensional array
# dtype allow us to specify a datatype for our ndarray
arr1 = np.array([1, 2, 3], dtype = np.float64)

# or do
arrint = arr1.astype(np.int32)

print(arr1)
print(arr1.dtype)
print(arrint.dtype)

[1. 2. 3.]
float64
int32


In [3]:
# Shows type of data for array
print(type(arr1))

<class 'numpy.ndarray'>


In [4]:
# Shows the "shape" of the array (For this case it shows 3 because arr1 is an array with 3 values in a 1-dimensional array)
print(arr1.shape)

(3,)


In [5]:
# Accessing the value of array just like accessing value in a list
arr1[0]

1

In [6]:
arr1[0] = 5
arr1[2] = 0
print(arr1)

[5 2 0]


==================================================================================================================================================================================

TWO-DIMENSIONAL ARRAY

In [7]:
# Creates a two-dimensional array
arr2 = np.array([[1, 2, 3], [3, 4, 5]])
print(arr2)

[[1 2 3]
 [3 4 5]]


In [8]:
# Accessing value inside a two-dimensional array
# First index represents array while the second index represents the value inside array
print(arr2[1][1])
# or we can do
print(arr2[1, 2])
 

4
5


In [9]:
# This will return (2, 3) which means 2 rows with 3 elements
print(arr2.shape)

(2, 3)


ARRAY CAN ALSO HOLD THINGS WHICH ARE NOT VALUES

In [10]:
arrS = np.array(["JW","TM"])
print(type(arrS))
arrS

<class 'numpy.ndarray'>


array(['JW', 'TM'], dtype='<U2')

==================================================================================================================================================================================

NUMPY FUNCTIONS

In [11]:
# Creates a one-dimensional array with a specified increment but does not include the last number
arrR = np.arange(0, 20, 2)
arrR

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
# linspace returns evenly spaced samples calculated over the interval 
# Basically show increments within a certain numbers 
arrL = np.linspace(0, 10, 20 )
arrL

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [13]:
# Creates a random array with the specified values in it between 0 to 1
arrR = np.random.rand(10)
arrR2 = np.random.rand(3, 4) # Creates a 3 row array 4 value array

print(arrR)
print(arrR2)


[0.0543511  0.20167099 0.82043039 0.74111968 0.18013058 0.72203657
 0.92282668 0.93526313 0.62913189 0.44709734]
[[0.7892768  0.78320504 0.16809639 0.51053189]
 [0.10442286 0.10317138 0.61473699 0.69631188]
 [0.37145803 0.34766944 0.72141789 0.62996703]]


In [14]:
# Creates a series of array with zeros as its values
print(f"{np.zeros(10)}\n{np.zeros((2, 3))}")

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
# 3-dimensional arrays (This case it means three 10 10s) \|_
print(np.ones((3, 10, 10)))

[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1

In [16]:
arr = [0, 1, 2]
print(np.repeat(arr, 3)) # Repeat the values in the specified array three times

[0 0 0 1 1 1 2 2 2]


In [17]:
print(np.tile(arr, 3)) # Repeats the array specified time

[0 1 2 0 1 2 0 1 2]


In [18]:
# Creates identity matrix with a specified row
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
np.diag([1, 2, 3, 4, 5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [20]:
arr = np.random.rand(5, 5)
print(arr)
arrDi = np.diag(arr) # Returns the diagonal array
print(f"\n{arrDi}")

[[0.63130231 0.76666977 0.84164719 0.97489858 0.73175727]
 [0.98610819 0.88915808 0.53820466 0.67686426 0.47539774]
 [0.45461989 0.87000461 0.07419416 0.03320387 0.89650993]
 [0.03519021 0.45990583 0.2034099  0.69349062 0.28053448]
 [0.93895954 0.67526169 0.2984781  0.74460625 0.25447888]]

[0.63130231 0.88915808 0.07419416 0.69349062 0.25447888]


In [21]:
print(arr.ndim) # Shows the dimension of the array
print(arr.size) # Shows the size of the array eg: 5 * 5 = 25
print(arr.shape) # Shows the grid of the array eg: 5, 5

2
25
(5, 5)


In [22]:
np.random.randint(-10, 10, 4) # Creates a random array (np.random.randint(start, end, array size))

array([-10,  -1,  -7,   2])

================================================================================================================================================================================

MODIFYING ARRAY VALUE

In [23]:
arr + 10 # Plus 10 to every element in the array

array([[10.63130231, 10.76666977, 10.84164719, 10.97489858, 10.73175727],
       [10.98610819, 10.88915808, 10.53820466, 10.67686426, 10.47539774],
       [10.45461989, 10.87000461, 10.07419416, 10.03320387, 10.89650993],
       [10.03519021, 10.45990583, 10.2034099 , 10.69349062, 10.28053448],
       [10.93895954, 10.67526169, 10.2984781 , 10.74460625, 10.25447888]])

In [24]:
np.exp(arr) # Returns the exponential array eg: e^[array_value]

array([[1.8800574 , 2.15258571, 2.32018563, 2.65089834, 2.07873029],
       [2.68078105, 2.43308034, 1.71292882, 1.96769787, 1.6086539 ],
       [1.57557439, 2.38692185, 1.0770159 , 1.03376127, 2.45103389],
       [1.03581671, 1.58392482, 1.22557473, 2.000687  , 1.32383719],
       [2.55731923, 1.96454701, 1.34780602, 2.10561218, 1.28978931]])

In [25]:
print(np.log(arr)) # Returns the log array eg: log10[array_value] by default
print("\n")
print(np.log2(arr)) # Returns the log base 2 array and etc

[[-0.45997044 -0.26569911 -0.17239436 -0.02542183 -0.31230642]
 [-0.0139892  -0.11748024 -0.61951638 -0.39028452 -0.74360347]
 [-0.78829361 -0.13925677 -2.60106983 -3.40508875 -0.10924591]
 [-3.34698733 -0.77673353 -1.59253211 -0.36601757 -1.27105862]
 [-0.06298289 -0.39265498 -1.20905872 -0.29489973 -1.36853745]]


[[-0.66359707 -0.38332279 -0.24871249 -0.03667595 -0.45056292]
 [-0.02018216 -0.16948815 -0.8937732  -0.56306154 -1.07279304]
 [-1.13726728 -0.20090505 -3.75255055 -4.91250465 -0.15760853]
 [-4.82868202 -1.12058961 -2.29753817 -0.52805173 -1.83374997]
 [-0.09086511 -0.56648139 -1.74430301 -0.42545038 -1.97438219]]


In [26]:
np.cos(arr) # Returns the cosine value obtained from array (sin for sine and tan)

array([[0.80725958, 0.72022497, 0.66623535, 0.561252  , 0.74400138],
       [0.55193935, 0.63006603, 0.85863035, 0.77954062, 0.88911075],
       [0.89842801, 0.64482302, 0.99724888, 0.9994488 , 0.62434004],
       [0.99938089, 0.8960943 , 0.97938344, 0.76901941, 0.96090759],
       [0.59062794, 0.7805434 , 0.95578513, 0.7353548 , 0.96779462]])

In [27]:
np.sum(arr, axis = 1) # Returns the sum of the whole array (axis = 0 means sum of the column while axis = 1 means that sum of the row)

array([3.94627512, 3.56573295, 2.32853247, 1.67253105, 2.91178444])

In [28]:
# Statistic functions

print(np.min(arr, axis = 0))
print(np.max(arr))
print(np.mean(arr, axis = 1))
print(np.median(arr))
print(np.std(arr, axis = 0))
print(np.var(arr))
# return the sum of i and i-1 
print(np.cumsum(arr))
# return the product of i and i-1
print(np.cumprod(arr))

#np.modf returns the decimal and the whole number of the ndarray E.g: 3.086 returns [3],[0.086]
remainder, wholepart = np.modf(arr)
print(remainder, wholepart)

[0.03519021 0.45990583 0.07419416 0.03320387 0.25447888]
0.9861081894938558
[0.78925502 0.71314659 0.46570649 0.33450621 0.58235689]
0.6752616873077708
[0.3477562  0.15633311 0.27161304 0.31443201 0.25145028]
0.08911789710010158
[ 0.63130231  1.39797208  2.23961928  3.21451785  3.94627512  4.93238331
  5.8215414   6.35974606  7.03661033  7.51200807  7.96662797  8.83663257
  8.91082673  8.94403061  9.84054054  9.87573075 10.33563658 10.53904648
 11.2325371  11.51307159 12.45203112 13.12729281 13.42577091 14.17037715
 14.42485603]
[6.31302307e-01 4.84000398e-01 4.07357576e-01 3.97132322e-01
 2.90604464e-01 2.86567441e-01 2.54803757e-01 1.37136571e-01
 9.28228440e-02 4.41277707e-02 2.00613625e-02 1.74534778e-02
 1.29494613e-03 4.29972271e-05 3.85474411e-05 1.35649259e-06
 6.23858850e-07 1.26899068e-07 8.80033135e-08 2.46879642e-08
 2.31809994e-08 1.56532408e-08 4.67214956e-09 3.47891174e-09
 8.85309549e-10]
[[0.63130231 0.76666977 0.84164719 0.97489858 0.73175727]
 [0.98610819 0.88915808 

In [29]:
# Slicing
# The example below is showing starting from the index 1 array, and starting from the 2nd value inside array
arr[1:, 2:4] 

array([[0.53820466, 0.67686426],
       [0.07419416, 0.03320387],
       [0.2034099 , 0.69349062],
       [0.2984781 , 0.74460625]])

In [30]:
# Sorting array values
np.sort(arr, axis = 0) 

array([[0.03519021, 0.45990583, 0.07419416, 0.03320387, 0.25447888],
       [0.45461989, 0.67526169, 0.2034099 , 0.67686426, 0.28053448],
       [0.63130231, 0.76666977, 0.2984781 , 0.69349062, 0.47539774],
       [0.93895954, 0.87000461, 0.53820466, 0.74460625, 0.73175727],
       [0.98610819, 0.88915808, 0.84164719, 0.97489858, 0.89650993]])

In [31]:
print(f"This is the normal array \n{arr}")
print(f"\nThis is the tranposed array \n{arr.T}")
# Tranposed array converts the array to sort by column
# For example: a 5 x 3 array becomes a 3 x 5 array 
print(f"\nSlicing tranposed array \n{arr[:3,:].T} ")
# We have to -1(for the end slice) everytime. Eg: 0:4 means 0, 1, 2, 3 

This is the normal array 
[[0.63130231 0.76666977 0.84164719 0.97489858 0.73175727]
 [0.98610819 0.88915808 0.53820466 0.67686426 0.47539774]
 [0.45461989 0.87000461 0.07419416 0.03320387 0.89650993]
 [0.03519021 0.45990583 0.2034099  0.69349062 0.28053448]
 [0.93895954 0.67526169 0.2984781  0.74460625 0.25447888]]

This is the tranposed array 
[[0.63130231 0.98610819 0.45461989 0.03519021 0.93895954]
 [0.76666977 0.88915808 0.87000461 0.45990583 0.67526169]
 [0.84164719 0.53820466 0.07419416 0.2034099  0.2984781 ]
 [0.97489858 0.67686426 0.03320387 0.69349062 0.74460625]
 [0.73175727 0.47539774 0.89650993 0.28053448 0.25447888]]

Slicing tranposed array 
[[0.63130231 0.98610819 0.45461989]
 [0.76666977 0.88915808 0.87000461]
 [0.84164719 0.53820466 0.07419416]
 [0.97489858 0.67686426 0.03320387]
 [0.73175727 0.47539774 0.89650993]] 


In [32]:
# Converts the array into a 1 x n array (useful for neural networks)
arr[1:4, :3].flatten()

array([0.98610819, 0.88915808, 0.53820466, 0.45461989, 0.87000461,
       0.07419416, 0.03519021, 0.45990583, 0.2034099 ])

In [33]:
# Appending things into array
# But normally people process the data then put it as array instead of adding new stuffs to array
arr = np.array([1, 2, 3, 4, 5])
arrpin = np.append(arr, [6, 7, 8])
arr_insert = np.insert(arr, 1, [1, 2, 3]) # np.insert(array, index, value)

print(f"{arr}\n{arrpin}\n{arr_insert}")

[1 2 3 4 5]
[1 2 3 4 5 6 7 8]
[1 1 2 3 2 3 4 5]


In [34]:
arr_del = np.delete(arr_insert, [0]) # np.delete(array, [index], axis)
print(arr_del)

[1 2 3 2 3 4 5]


In [35]:
# Copying array
arrC = arr_del.copy()
print(arrC)

[1 2 3 2 3 4 5]


=======================================================================================================================================

NUMPY BOOLEAN METHODS

In [36]:
arr = np.random.randn(50)
# Returns the total number of true elements
(arr > 0).sum() 

23

In [39]:
bools = np.array([False, False, True, False])
print(bools.any())
print(bools.all())  

True
False


===================================================================================================================================

NUMPY SET AND MATRICES FUNCTIONS

In [47]:
# Concatenating arrays (Combining arrays)
arr1 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
arr2 = np.array([[5, 6, 7, 8, 9], [5, 6, 7, 8, 9]])
arr_cat = np.concatenate((arr1, arr2), axis = 1)
print(arr_cat)

[[1 2 3 4 5 5 6 7 8 9]
 [1 2 3 4 5 5 6 7 8 9]]


In [48]:
# Similar to concatenate but it does not require axis (vstack stands for vertical stack)
catV = np.vstack((arr1, arr2))
print(catV)

# hstack stands for horizontal stack
catH = np.hstack((arr1, arr2))
print(catH)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [5 6 7 8 9]
 [5 6 7 8 9]]
[[1 2 3 4 5 5 6 7 8 9]
 [1 2 3 4 5 5 6 7 8 9]]


In [49]:
arr = np.array([1, 2, 3, 4, 5, 7, 3, 2, 5, 3])
print(np.unique(arr)) # Returns all the unique value inside the array

[1 2 3 4 5 7]


In [50]:
# returns two variable, unique value inside array and return its counts
uniques, countsw = np.unique(arr, return_counts = True)
print(uniques)
print(countsw)

[1 2 3 4 5 7]
[1 2 3 1 2 1]


In [51]:
# Intersection, differentiation, neither
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])
print(np.intersect1d(arr1, arr2)) # Returns the same value occured in both arrays
print(np.union1d(arr1, arr2)) # Returns everything occured in both array (but only show one if there are repeating value)
# np.setdiff1d(targetset, secondset)
print(np.setdiff1d(arr2, arr1)) # Returns the difference between the targetted set and the other set (only shows the target set)
print(np.setxor1d(arr1, arr2)) # Returns all the difference between both arrays


[3 4 5]
[1 2 3 4 5 6 7]
[6 7]
[1 2 6 7]


=======================================================================================================================================


Book Examples

In [52]:
arrx = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
arry = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

result = [(x if c else y)for x, y, c in zip(arrx, arry, cond)]
print(result)

# This can be interpreted as 
result = np.where(cond, arrx, arry)
print(result)

[1.1, 2.2, 1.3, 1.4, 2.5]
[1.1 2.2 1.3 1.4 2.5]


In [53]:
arr = np.empty((4, 4))

list = [4, 3, 0, 6] 
for el in list:
    for i in range(4):
        arr[i] = list[i]

arr

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])