ONE-DIMENSIONAL ARRAY

In [2]:
import numpy as np 

# Creates a one dimensional array
arr1 = np.array([1, 2, 3])

print(arr1)

[1 2 3]


In [3]:
# Shows type of data for array
print(type(arr1))

<class 'numpy.ndarray'>


In [4]:
# Shows the "shape" of the array (For this case it shows 3 because arr1 is an array with 3 values in a 1-dimensional array)
print(arr1.shape)

(3,)


In [5]:
# Accessing the value of array just like accessing value in a list
arr1[0]

1

In [6]:
arr1[0] = 5
arr1[2] = 0
print(arr1)

[5 2 0]


==================================================================================================================================================================================

TWO-DIMENSIONAL ARRAY

In [7]:
# Creates a two-dimensional array
arr2 = np.array([[1, 2, 3], [3, 4, 5]])
print(arr2)

[[1 2 3]
 [3 4 5]]


In [8]:
# Accessing value inside a two-dimensional array
# First index represents array while the second index represents the value inside array
print(arr2[1][1])
# or we can do
print(arr2[1, 2])
 

4
5


In [9]:
# This will return (2, 3) which means 2 rows with 3 elements
print(arr2.shape)

(2, 3)


ARRAY CAN ALSO HOLD THINGS WHICH ARE NOT VALUES

In [10]:
arrS = np.array(["JW","TM"])
print(type(arrS))
arrS

<class 'numpy.ndarray'>


array(['JW', 'TM'], dtype='<U2')

==================================================================================================================================================================================

NUMPY FUNCTIONS

In [11]:
# Creates a one-dimensional array with a specified increment but does not include the last number
arrR = np.arange(0, 20, 2)
arrR

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
# linspace returns evenly spaced samples calculated over the interval 
# Basically show increments within a certain numbers 
arrL = np.linspace(0, 10, 20 )
arrL

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [13]:
# Creates a random array with the specified values in it between 0 to 1
arrR = np.random.rand(10)
arrR2 = np.random.rand(3, 4) # Creates a 3 row array 4 value array

print(arrR)
print(arrR2)


[0.13064585 0.63764961 0.2521255  0.93218029 0.00531661 0.1556422
 0.8970725  0.14558052 0.50172339 0.8706788 ]
[[0.78863989 0.71934838 0.70413562 0.52347404]
 [0.42306312 0.78991542 0.49708312 0.03885568]
 [0.19886658 0.36805842 0.19368495 0.22066731]]


In [14]:
# Creates a series of array with zeros as its values
print(f"{np.zeros(10)}\n{np.zeros((2, 3))}")

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
# 3-dimensional arrays (This case it means three 10 10s) \|_
print(np.ones((3, 10, 10)))

[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1

In [16]:
arr = [0, 1, 2]
print(np.repeat(arr, 3)) # Repeat the values in the specified array three times

[0 0 0 1 1 1 2 2 2]


In [17]:
print(np.tile(arr, 3)) # Repeats the array specified time

[0 1 2 0 1 2 0 1 2]


In [18]:
# Creates identity matrix with a specified row
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
np.diag([1, 2, 3, 4, 5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [20]:
arr = np.random.rand(5, 5)
print(arr)
arrDi = np.diag(arr) # Returns the diagonal array
print(f"\n{arrDi}")

[[0.67875408 0.68487981 0.17736671 0.37226749 0.81509165]
 [0.65923662 0.33390226 0.10277504 0.92422151 0.59565925]
 [0.89223596 0.60639015 0.29601643 0.87134307 0.52127438]
 [0.09162109 0.11741324 0.90302062 0.9741594  0.67428728]
 [0.32727675 0.4767501  0.24529425 0.04184565 0.93991953]]

[0.67875408 0.33390226 0.29601643 0.9741594  0.93991953]


In [21]:
print(arr.ndim) # Shows the dimension of the array
print(arr.size) # Shows the size of the array eg: 5 * 5 = 25
print(arr.shape) # Shows the grid of the array eg: 5, 5

2
25
(5, 5)


In [22]:
np.random.randint(-10, 10, 4) # Creates a random array (np.random.randint(start, end, array size))

array([ 8,  3, -7,  9])

================================================================================================================================================================================

MODIFYING ARRAY VALUE

In [23]:
arr + 10 # Plus 10 to every element in the array

array([[10.67875408, 10.68487981, 10.17736671, 10.37226749, 10.81509165],
       [10.65923662, 10.33390226, 10.10277504, 10.92422151, 10.59565925],
       [10.89223596, 10.60639015, 10.29601643, 10.87134307, 10.52127438],
       [10.09162109, 10.11741324, 10.90302062, 10.9741594 , 10.67428728],
       [10.32727675, 10.4767501 , 10.24529425, 10.04184565, 10.93991953]])

In [24]:
np.exp(arr) # Returns the exponential array eg: e^[array_value]

array([[1.97141998, 1.98353342, 1.19406889, 1.45102107, 2.25938272],
       [1.93331593, 1.39640665, 1.10824207, 2.51990577, 1.81422657],
       [2.44058058, 1.8337997 , 1.34449224, 2.39011879, 1.68417257],
       [1.09594947, 1.12458406, 2.46704387, 2.64893958, 1.96263366],
       [1.38718532, 1.61083084, 1.27799731, 1.04273352, 2.55977543]])

In [25]:
print(np.log(arr)) # Returns the log array eg: log10[array_value] by default
print("\n")
print(np.log2(arr)) # Returns the log base 2 array and etc

[[-0.38749639 -0.37851191 -1.72953589 -0.98814261 -0.20445472]
 [-0.41667274 -1.09690696 -2.27521279 -0.07880351 -0.51808651]
 [-0.11402466 -0.50023168 -1.21734033 -0.1377195  -0.65147873]
 [-2.39009384 -2.14205556 -0.10200989 -0.02618033 -0.39409903]
 [-1.11694915 -0.74076283 -1.40529678 -3.17376735 -0.06196101]]


[[-0.55903912 -0.54607726 -2.49519285 -1.42558845 -0.29496582]
 [-0.6011317  -1.58250223 -3.2824382  -0.11368943 -0.74744084]
 [-0.16450281 -0.72168177 -1.75625086 -0.19868724 -0.93988513]
 [-3.44817653 -3.09033293 -0.14716917 -0.03777024 -0.56856472]
 [-1.611417   -1.06869486 -2.02741469 -4.57877841 -0.08939085]]


In [26]:
np.cos(arr) # Returns the cosine value obtained from array (sin for sine and tan)

array([[0.77835554, 0.77449508, 0.98431172, 0.93150499, 0.6858017 ],
       [0.79046004, 0.94477064, 0.99472329, 0.60245613, 0.82777881],
       [0.62767296, 0.82171064, 0.95650613, 0.64379942, 0.86718526],
       [0.99580572, 0.99311498, 0.619241  , 0.56186362, 0.78115213],
       [0.94692129, 0.88849097, 0.97006591, 0.9991246 , 0.58985301]])

In [27]:
np.sum(arr, axis = 1) # Returns the sum of the whole array (axis = 0 means sum of the column while axis = 1 means that sum of the row)

array([2.72835974, 2.61579468, 3.18725999, 2.76050163, 2.03108628])

In [28]:
# Statistic functions

print(np.min(arr, axis = 0))
print(np.max(arr))
print(np.mean(arr, axis = 1))
print(np.median(arr))
print(np.std(arr, axis = 0))
print(np.var(arr))


[0.09162109 0.11741324 0.10277504 0.04184565 0.52127438]
0.9741594006033557
[0.54567195 0.52315894 0.637452   0.55210033 0.40621726]
0.5956592457920281
[0.28401317 0.20211212 0.28653148 0.36752716 0.15091121]
0.08932646406048778


In [29]:
# Slicing
# The example below is showing starting from the index 1 array, and starting from the 2nd value inside array
arr[1:, 2:4] 

array([[0.10277504, 0.92422151],
       [0.29601643, 0.87134307],
       [0.90302062, 0.9741594 ],
       [0.24529425, 0.04184565]])

In [30]:
# Sorting array values
np.sort(arr, axis = 0) 

array([[0.09162109, 0.11741324, 0.10277504, 0.04184565, 0.52127438],
       [0.32727675, 0.33390226, 0.17736671, 0.37226749, 0.59565925],
       [0.65923662, 0.4767501 , 0.24529425, 0.87134307, 0.67428728],
       [0.67875408, 0.60639015, 0.29601643, 0.92422151, 0.81509165],
       [0.89223596, 0.68487981, 0.90302062, 0.9741594 , 0.93991953]])

In [31]:
print(f"This is the normal array \n{arr}")
print(f"\nThis is the tranposed array \n{arr.T}")
# Tranposed array converts the array to sort by column
# For example: a 5 x 3 array becomes a 3 x 5 array 
print(f"\nSlicing tranposed array \n{arr[:3,:].T} ")
# We have to -1(for the end slice) everytime. Eg: 0:4 means 0, 1, 2, 3 

This is the normal array 
[[0.67875408 0.68487981 0.17736671 0.37226749 0.81509165]
 [0.65923662 0.33390226 0.10277504 0.92422151 0.59565925]
 [0.89223596 0.60639015 0.29601643 0.87134307 0.52127438]
 [0.09162109 0.11741324 0.90302062 0.9741594  0.67428728]
 [0.32727675 0.4767501  0.24529425 0.04184565 0.93991953]]

This is the tranposed array 
[[0.67875408 0.65923662 0.89223596 0.09162109 0.32727675]
 [0.68487981 0.33390226 0.60639015 0.11741324 0.4767501 ]
 [0.17736671 0.10277504 0.29601643 0.90302062 0.24529425]
 [0.37226749 0.92422151 0.87134307 0.9741594  0.04184565]
 [0.81509165 0.59565925 0.52127438 0.67428728 0.93991953]]

Slicing tranposed array 
[[0.67875408 0.65923662 0.89223596]
 [0.68487981 0.33390226 0.60639015]
 [0.17736671 0.10277504 0.29601643]
 [0.37226749 0.92422151 0.87134307]
 [0.81509165 0.59565925 0.52127438]] 


In [32]:
# Converts the array into a 1 x n array (useful for neural networks)
arr[1:4, :3].flatten()

array([0.65923662, 0.33390226, 0.10277504, 0.89223596, 0.60639015,
       0.29601643, 0.09162109, 0.11741324, 0.90302062])

In [33]:
# Appending things into array
# But normally people process the data then put it as array instead of adding new stuffs to array
arr = np.array([1, 2, 3, 4, 5])
arrpin = np.append(arr, [6, 7, 8])
arr_insert = np.insert(arr, 1, [1, 2, 3]) # np.insert(array, index, value)

print(f"{arr}\n{arrpin}\n{arr_insert}")

[1 2 3 4 5]
[1 2 3 4 5 6 7 8]
[1 1 2 3 2 3 4 5]


In [34]:
arr_del = np.delete(arr_insert, [0]) # np.delete(array, [index], axis)
print(arr_del)

[1 2 3 2 3 4 5]


In [35]:
# Copying array
arrC = arr_del.copy()
print(arrC)

[1 2 3 2 3 4 5]


===================================================================================================================================

NUMPY SET AND MATRICES FUNCTIONS

In [36]:
# Concatenating arrays (Combining arrays)
arr1 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
arr2 = np.array([[5, 6, 7, 8, 9], [5, 6, 7, 8, 9]])
arr_cat = np.concatenate((arr1, arr2), axis = 1)
print(arr_cat)

[[1 2 3 4 5 5 6 7 8 9]
 [1 2 3 4 5 5 6 7 8 9]]


In [38]:
# Similar to concatenate but it does not require axis (vstack stands for vertical stack)
catV = np.vstack((arr1, arr2))
print(catV)

# hstack stands for horizontal stack
catH = np.hstack((arr1, arr2))
print(catH)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [5 6 7 8 9]
 [5 6 7 8 9]]
[[1 2 3 4 5 5 6 7 8 9]
 [1 2 3 4 5 5 6 7 8 9]]


In [42]:
arr = np.array([1, 2, 3, 4, 5, 7, 3, 2, 5, 3])
print(np.unique(arr)) # Returns all the unique value inside the array

[1 2 3 4 5 7]


In [45]:
# returns two variable, unique value inside array and return its counts
uniques, countsw = np.unique(arr, return_counts = True)
print(uniques)
print(countsw)

(array([1, 2, 3, 4, 5, 7]), array([1, 2, 3, 1, 2, 1], dtype=int64))


In [53]:
# Intersection, differentiation, neither
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])
print(np.intersect1d(arr1, arr2)) # Returns the same value occured in both arrays
print(np.union1d(arr1, arr2)) # Returns everything occured in both array (but only show one if there are repeating value)
# np.setdiff1d(targetset, secondset)
print(np.setdiff1d(arr2, arr1)) # Returns the difference between the targetted set and the other set (only shows the target set)
print(np.setxor1d(arr1, arr2)) # Returns all the difference between both arrays


[3 4 5]
[1 2 3 4 5 6 7]
[6 7]
