# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)

1.20.1


#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [6]:
arr = np.random.rand(5, 5)
print(arr)
size = arr.size * arr.itemsize
print(f"{size} bytes")

[[0.44398657 0.32005326 0.29194484 0.11464442 0.65129651]
 [0.47278522 0.16673544 0.08268772 0.84541669 0.39447125]
 [0.28037939 0.2805609  0.0166362  0.06351162 0.36845036]
 [0.86302731 0.33444768 0.24151857 0.8296518  0.63290341]
 [0.51524176 0.4223634  0.99960087 0.62747849 0.36269236]]
200 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
# %run 'python -c "import numpy; numpy.info(numpy.add)"'

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
arr = np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [10]:
arr[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [12]:
# Returns the indices of elements which are not zero
nz = np.nonzero([1,2,0,0,4,0])
print(nz)


(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [13]:
# np.eye = identity matrix
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [14]:
rand = np.random.random((3, 3, 3))
randarr = np.random.rand(3,3,3)
print(randarr)
print(rand)

[[[0.03272071 0.42550749 0.74210341]
  [0.83112462 0.19160943 0.63895393]
  [0.8759932  0.33647552 0.42651431]]

 [[0.17974562 0.81654515 0.4734809 ]
  [0.80626991 0.00505171 0.35688209]
  [0.24872636 0.29704816 0.9822091 ]]

 [[0.93938151 0.53626359 0.24065802]
  [0.8340117  0.84898471 0.41163429]
  [0.77712836 0.91704943 0.45277018]]]
[[[0.41343072 0.10517496 0.93831205]
  [0.21178049 0.92547651 0.71724091]
  [0.86412755 0.79974492 0.73922348]]

 [[0.71764016 0.53100929 0.28362647]
  [0.2569519  0.99172993 0.31021219]
  [0.20523143 0.78399016 0.85971058]]

 [[0.03759733 0.83250873 0.44894718]
  [0.8703261  0.93959604 0.39483671]
  [0.18711176 0.31435924 0.83438081]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [15]:
arr = np.random.rand(10, 10)
print(arr)
print(f"Maximum in array = {np.max(arr)}")
print(f"Minimum in array = {np.min(arr)}")

[[0.32263479 0.78744019 0.03253116 0.92126022 0.08463401 0.56419479
  0.59325138 0.2259289  0.00970416 0.69164431]
 [0.50587296 0.42674852 0.71165393 0.96471029 0.80540635 0.5156428
  0.15882604 0.94728047 0.68165142 0.77749565]
 [0.60607039 0.89488934 0.43161896 0.42069071 0.83192549 0.26894793
  0.47262284 0.32155455 0.28443527 0.07555127]
 [0.20931349 0.92994807 0.86117637 0.09501573 0.74883851 0.03438186
  0.87106548 0.93696026 0.63052543 0.27427648]
 [0.08777489 0.73026955 0.58403871 0.73004862 0.94899971 0.10153641
  0.55582028 0.50481118 0.75929322 0.93016939]
 [0.44999061 0.73864613 0.81353942 0.2454016  0.99758157 0.21301437
  0.17499889 0.71235934 0.37661116 0.44975542]
 [0.7109683  0.74832665 0.79230552 0.74496905 0.88971598 0.1128909
  0.78563591 0.80590723 0.25085749 0.07347273]
 [0.13739303 0.88324646 0.87052844 0.39486256 0.46397569 0.58095417
  0.57883515 0.04738223 0.13078446 0.95732394]
 [0.79358517 0.67604657 0.02972971 0.8455553  0.61197445 0.61577898
  0.55753172 0

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [16]:
arr = np.random.rand(30,1)
print(arr)
print(f"Array mean = {np.mean(arr)}")

[[0.85391372]
 [0.98719835]
 [0.22947736]
 [0.41515006]
 [0.18709995]
 [0.96064324]
 [0.11372379]
 [0.07301045]
 [0.71150045]
 [0.32061545]
 [0.01011817]
 [0.46508126]
 [0.9787716 ]
 [0.86044792]
 [0.61414425]
 [0.54888457]
 [0.05250721]
 [0.65968779]
 [0.45681497]
 [0.81862872]
 [0.12636681]
 [0.48733698]
 [0.8078213 ]
 [0.4233773 ]
 [0.89948846]
 [0.52157726]
 [0.87120201]
 [0.06354314]
 [0.51303928]
 [0.46358321]]
Array mean = 0.5164918339606548


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [17]:
arr = np.ones((5, 5))
arr[1: -1, 1: -1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [18]:
arr = np.ones((5, 5))
arr = np.pad(arr, 1, mode = 'constant', constant_values = 0)
print(arr)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [19]:
# nan
print(0 * np.nan)

# False
print(np.nan == np.nan)

# False
print(np.inf > np.nan)

# nan
print(np.nan - np.nan)

# True
print(np.nan in set([np.nan]))

# False
print(0.3 == 3 * 0.1)


nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [20]:
np.diag(np.arange(4) + 1, k = 0)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [21]:
arr = np.zeros((8, 8))
arr[1::2,::2] = 1
arr[::2,1::2] = 1

print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [22]:
np.unravel_index(99, (6, 7, 8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [30]:
arr = np.tile(np.array([[1,0],[0,1]]), (4,4))
print(arr)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [35]:
arr = np.random.rand(5, 5)
# Normalize = Z value
normalised = ((arr - np.mean(arr)) / np.std(arr))
print(f"Original array: {arr}")
print(normalised)

Original array: [[0.45864343 0.98701756 0.98495449 0.17771174 0.56947676]
 [0.94408803 0.8358364  0.09957999 0.68138089 0.39074824]
 [0.30501662 0.55529081 0.21538737 0.35368872 0.31932953]
 [0.63169858 0.45411724 0.03904813 0.20619225 0.31961294]
 [0.35644262 0.94893098 0.51300001 0.17990047 0.89656757]]
[[-0.13194842  1.68822449  1.68111753 -1.0997177   0.24985647]
 [ 1.54033844  1.16742713 -1.36887032  0.63535012 -0.36583757]
 [-0.66117069  0.2009879  -0.96993057 -0.49350231 -0.61186477]
 [ 0.46420168 -0.14754048 -1.57739389 -1.00160644 -0.61088848]
 [-0.4840155   1.5570217   0.0553022  -1.09217783  1.37663729]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [38]:
colour_code = np.dtype([("r", np.ubyte),
                        ("g", np.ubyte),
                        ("b", np.ubyte),
                        ("a", np.ubyte)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)